# Generated by Django 4.2.7 on 2023-12-03 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('pharmacyName', models.CharField(max_length=250)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('totalPrice', models.PositiveBigIntegerField()),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DebtProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveBigIntegerField()),
                ('pricePerProduct', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
                ('sellingPrice', models.PositiveBigIntegerField()),
                ('totalStock', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveBigIntegerField()),
                ('totalPrice', models.PositiveBigIntegerField()),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveBigIntegerField()),
                ('pricePerProduct', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveBigIntegerField()),
                ('pricePerProduct', models.PositiveIntegerField()),
                ('expiryDate', models.DateField()),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
