# Generated by Django 4.2.7 on 2023-12-03 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy_sys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='pharmacyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stock',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_sys.product'),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_sys.product'),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='sellId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_sys.sell'),
        ),
        migrations.AddField(
            model_name='sell',
            name='pharmacyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_sys.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='pharmacyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='debtproduct',
            name='debtId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_sys.debt'),
        ),
        migrations.AddField(
            model_name='debtproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_sys.product'),
        ),
        migrations.AddField(
            model_name='debt',
            name='clientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_sys.client'),
        ),
        migrations.AddField(
            model_name='client',
            name='pharmacyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='pharmacyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
